### ISSUE TITLE
Error in payment confirmation and return

### ISSUE THREAD

**Issue by heberq** [imiguelsalcedo/gateway-mercadopago-blesta#2] opened 2024-10-26 17:31 UTC
I am using the current version of Blesta and the Mercado Livre gateway is giving an error when it is supposed to confirm the payment.
Is there any way to correct this error please?

Thank you
Heber

**Comment by imiguelsalcedo** [comment] 2024-10-26 17:57
Hi Heber, could you send the error message?

**Comment by diegoweb** [comment] 2024-11-19 02:04
Hey! I'm having the same issue.
My clients can pay using MercadoPago, but Blesta is not closing the invoices.


This is what I'm getting in Blesta:
![chrome_18-11-2024_23-02-54](https://github.com/user-attachments/assets/b634c2a4-6f43-4b05-9cef-dea8a86da472)


And this is what MercadoPago is telling me to fix:
![chrome_18-11-2024_23-03-55](https://github.com/user-attachments/assets/83ec9be1-eeb5-4265-b0d8-a7ba451347c0)
![chrome_18-11-2024_23-04-11](https://github.com/user-attachments/assets/3abec5f9-3bba-4464-98b8-41afb0a71bb5)

**Comment by heberq** [comment] 2024-11-21 14:51
> Hi Heber, could you send the error message?

After the blesta update, if I install the Gateway, my blesta stops opening. So now I can't even check the error anymore.
If you can get the data from diegoweb, it would be easier, because it seems he hasn't updated the blesta yet.

**Comment by imiguelsalcedo** [comment] 2024-11-22 15:51
@diegoweb Hi Diego, thanks for the information. I will apply it and probably update it shortly.

**Comment by imiguelsalcedo** [comment] 2024-11-22 19:54
I have added the parameters you suggest, and with the test account it completes the payment successfully.

**Comment by diegoweb** [comment] 2024-11-25 20:14
> I have added the parameters you suggest, and with the test account it completes the payment successfully.

It indeed is completing the payment in Mercado Pago developer's panel after upgrading this gateway in Blesta:
![image](https://github.com/user-attachments/assets/b31b562b-3914-4f70-9ecb-58a4301f389a)

In mercado pago this invoice 330 is already showing as paid:
![image](https://github.com/user-attachments/assets/8c7eb45b-da70-40f5-a636-78565ee1620b)

But in Blesta it still shows the invoice as "Open":
![image](https://github.com/user-attachments/assets/6801c107-649c-49b9-bd4b-9f8712fea99b)

And in Blesta's gateway logs, I can't see any log for today (and the payment was done today).

All crons are working, so I'm not sure what is happening.
Even Blesta is updated.

**Comment by imiguelsalcedo** [comment] 2024-11-26 14:32
Hi @diegoweb , did you check if there were any error messages in the blesta log files?

**Comment by imiguelsalcedo** [comment] 2024-11-26 14:42
@diegoweb I also tested in production and it worked without problems.

![mp](https://github.com/user-attachments/assets/e89da6ef-35a5-4295-bb43-289b7a9a237a)

**Comment by diegoweb** [comment] 2024-11-27 03:05
> Hi @diegoweb , did you check if there were any error messages in the blesta log files?

That's the thing, no log was generated for mercado pago gateway (after updating the plugin and Blesta)
The plugin was working great for 1 client, but other 2 was having issue before the update. But at least it was generating logs.
After updating (both plugin and blesta itself), one client paid via mercado pago but no log was reported in Blesta.
And the one client that used to work, I still don't know if it will work next month. He's billing date is every 10th, so I will soon know if for him it's still working.

Weird... Even Mercadopago developer panel says the transaction was identified and everything was send correctly via api.
Just Blesta is acting weird.

**Comment by imiguelsalcedo** [comment] 2024-11-27 13:14
@diegoweb Something similar is happening to me, but with PayPal, it doesn't register anything at all.
Write to _MercadoPago_ support to see if they can give you any information.

**Closed as completed** 2024-12-01 11:40 UTC

**Comment by diegoweb** [comment] 2024-12-23 22:02
Hey @imiguelsalcedo MercadoPago replied, saying:

> Hello
> 
> As you can see from our notification logs, your integration is returning 403 error:
> ![mercadopago](https://github.com/user-attachments/assets/1bfa2c9d-c09b-41be-9e64-0859d58c6b9e)
> It's necessary that you test this URL with your plugin to see if there's any type of restriction either by the plugin or your hosting server via their firewall or other security plugin.
> 
> These are the IP's that need to be allowed in your plugin/firewall:
> 54.88.218.97
> 18.215.140.160
> 18.213.114.129
> 18.206.34.84

There's no IP Block/BAN in my server for those IPs, and I can't visit the URL that is showed in their screenshot. Should that URL be public accessible? Not even logged as admin in Blesta I can visit that URL.

**Comment by heberq** [comment] 2024-12-23 23:35
Hello Diego, I'm not having any problems on my server. Do you use Cloudflare?
If you use any external resources, take a look, as this may be your problem.

**Comment by diegoweb** [comment] 2024-12-23 23:55
> Hello Diego, I'm not having any problems on my server. Do you use Cloudflare? If you use any external resources, take a look, as this may be your problem.

I do use Cloudflare. Do you have any idea what to do to allow those IPs but keep the dns record proxied?
I have just created a WAF Rule, but I'm still not sure if that URL that MercadoPago support reported should be accessible via browser.

My blesta is running in an cPanel enviroment, but there's no IP blocked in there so far as I know.

> domain.com/callback/gw/1/mercadopago?client_id=10

**Comment by heberq** [comment] 2024-12-24 22:00
The idea I give you is to put the subdomain that is configured for blesta in DNS-only mode, so you will be sure of the error with Mercado Pago.

**Comment by imiguelsalcedo** [comment] 2024-12-26 19:52
Hi, I use Cloudflare and I had no problems. I did not create WAF rules or anything like that.

The problem I mentioned with paypal earlier was about my domain, it was rated as pishing in OpenDNS and after removing it all was solved.

**Comment by imiguelsalcedo** [comment] 2024-12-26 19:57
@diegoweb  It should not give error 403. Check the blesta logs. What version of php are you using?

You can try to modify the mercadopago.php file that is in the main folder of the gateway, in the line:  https://github.com/imiguelsalcedo/gateway-mercadopago-blesta/blob/b767f4609fc61a052113835c9a54b83f4426f4ef/mercadopago.php#L170C13-L171

You can use another server to receive the notification and rule out that the problem is on your side. webhook.site gives you a url for testing.

**Comment by diegoweb** [comment] 2024-12-26 23:15
> It should not give error 403.

If I visit that URL in my browser, I get ERROR 500.


> Check the blesta logs.

Funny enough Blesta Logs is correctly showing the return now, but I had to manually apply the balance to the client's account
![image](https://github.com/user-attachments/assets/2791ab3d-14c8-4781-9b18-e36f1b7b57f7)

I had manually applied the payment to this client's account in 20/12/2024 at 16:00h
After removing the Cloudflare proxy and creating the WAF Rule, this log above was recorded in 26/12/2024 - 18:57:41
So probably the next ones will be automatically closed.
Let's hope that's the case.....

> What version of php are you using?

I tried with PHP 8.1 and 8.2
